kind: pipeline
type: kubernetes
name: dev-build

trigger:
  branch:
  - development
  event:
  - custom

steps:
- name: "build server"
  image: docker.cloud.biggo.com/droneio/mattermost-funmula-build:latest
  commands:
  - make build-server
  - make build-package
  - cd server/build && cp -r ../dist packages

- name: "build docker image"
  image: docker.dev.cloud.biggo.com/test/plugin-docker
  settings:
    cache_from: docker.dev.cloud.biggo.com/test/mattermost:development
    registry: docker.dev.cloud.biggo.com
    repo: docker.dev.cloud.biggo.com/test/mattermost
    dockerfile: ./server/build/Dockerfile
    context: ./server/build/
    tags:
    - development