export IGNORE_GO_WORK_IF_EXISTS=true

export MM_SERVICEENVIRONMENT=production
export MM_LICENSE=eyJpZCI6IjJSbmxDN3NkME42bk9OYmpsZVNSS0ZBVUY4IiwiaXNzdWVkX2F0IjoxNzE1MTQ0MjMzNzgxLCJzdGFydHNfYXQiOjE3MTUxNDQyMzM3ODEsImV4cGlyZXNfYXQiOjE3NDY2ODAyMzM3ODEsImN1c3RvbWVyIjp7ImlkIjoiYmlnZ29fZGV2X3RlYW0iLCJuYW1lIjoiQiFnR28gRGV2ZWxvcG1lbnQiLCJlbWFpbCI6InJvb3RAbG9jYWxob3N0IiwiY29tcGFueSI6IkZ1bm11bGEifSwiZmVhdHVyZXMiOnsidXNlcnMiOm51bGwsImxkYXAiOmZhbHNlLCJsZGFwX2dyb3VwcyI6ZmFsc2UsIm1mYSI6ZmFsc2UsImdvb2dsZV9vYXV0aCI6ZmFsc2UsIm9mZmljZTM2NV9vYXV0aCI6ZmFsc2UsIm9wZW5pZCI6ZmFsc2UsImNvbXBsaWFuY2UiOmZhbHNlLCJjbHVzdGVyIjp0cnVlLCJtZXRyaWNzIjpmYWxzZSwibWhwbnMiOmZhbHNlLCJzYW1sIjpmYWxzZSwiZWxhc3RpY19zZWFyY2giOnRydWUsImFubm91bmNlbWVudCI6ZmFsc2UsInRoZW1lX21hbmFnZW1lbnQiOmZhbHNlLCJlbWFpbF9ub3RpZmljYXRpb25fY29udGVudHMiOmZhbHNlLCJkYXRhX3JldGVudGlvbiI6ZmFsc2UsIm1lc3NhZ2VfZXhwb3J0IjpmYWxzZSwiY3VzdG9tX3Blcm1pc3Npb25zX3NjaGVtZXMiOmZhbHNlLCJjdXN0b21fdGVybXNfb2Zfc2VydmljZSI6ZmFsc2UsImd1ZXN0X2FjY291bnRzIjpmYWxzZSwiZ3Vlc3RfYWNjb3VudHNfcGVybWlzc2lvbnMiOmZhbHNlLCJpZF9sb2FkZWQiOmZhbHNlLCJsb2NrX3RlYW1tYXRlX25hbWVfZGlzcGxheSI6ZmFsc2UsImVudGVycHJpc2VfcGx1Z2lucyI6ZmFsc2UsImFkdmFuY2VkX2xvZ2dpbmciOmZhbHNlLCJjbG91ZCI6ZmFsc2UsInNoYXJlZF9jaGFubmVscyI6ZmFsc2UsInJlbW90ZV9jbHVzdGVyX3NlcnZpY2UiOnRydWUsIm91dGdvaW5nX29hdXRoX2Nvbm5lY3Rpb25zIjpmYWxzZSwiZnV0dXJlX2ZlYXR1cmVzIjpmYWxzZX0sInNrdV9uYW1lIjoiQiFnR28gTHRkLiIsInNrdV9zaG9ydF9uYW1lIjoiQiFnR28iLCJpc190cmlhbCI6ZmFsc2UsImlzX2dvdl9za3UiOnRydWUsInNpZ251cF9qd3QiOm51bGx9LDhgNv5ThXFsUnit/h5Rs7ewjQUyn+4k9dS4Ud/9aPhI1VRuth0Q3m0+OGaD5S1C/X1YWFVVHQfgYsNN/F0UajNy7hgx7jgPH+CoggZyHhBf+d/og1bLHWBkgZKKFdeacZkwTIWZkGkIbfKS4tOeN15jAOlhGDj3BTiuLtJwgGTuWuBn1BQJVnr8SlSeTwyKpbxkf5YOsmrqzLvwKxfJgrxRD51SxjLVEXT8bVPS5q4T1+bSo1JJCJqVAC3CyCuFjZMNJMPydC29ws/oolFjfzZL4j1NMWiwncY8dbJpsfwNrFVsdOGhf3Y7mlRi/2ocIlWSmCNlYdT+4Oy8IFTUog==

build: build-server build-package

build-package:
	cd server && $(MAKE) package

build-server:
	cd server && $(MAKE) build

run: run-server run-client

run-client:
	cd server && $(MAKE) run-client

run-server:
	cd server && $(MAKE) run-server

stop: stop-client stop-server

stop-client:
	cd server && $(MAKE) stop-client

stop-server:
	cd server && $(MAKE) stop-server

restart: restart-server restart-client

restart-server:
	cd server && $(MAKE) restart-server

restart-client:
	cd server && $(MAKE) restart-client
