apiVersion: v1
stringData:
  DB_CONNECTION_STRING: >-
    postgres://{{ .Values.postgres.username }}:{{ .Values.postgres.password }}@{{ .Values.postgres.host }}:{{ .Values.postgres.port }}/{{ .Values.postgres.database }}?connect_timeout=10
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
stringData:
  accesskey: {{ .Values.minio.accesskey }}
  secretkey: {{ .Values.minio.secretkey }}
kind: Secret
metadata:
  name: {{ .Release.Name }}-minio-credential
  namespace: {{ .Release.Namespace }}
