apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-headless
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  clusterIPs:
    - None
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 8065
      protocol: TCP
      targetPort: 8065
    - name: rpc
      port: 8074
      protocol: TCP
      targetPort: 8074
  selector:
    app: {{ .Release.Name }}
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-loadbalancer
  annotations:
    {}
  labels:
    {}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    apps.kubernetes.io/pod-index: {{ .Values.service.podindex }}
    app: {{ .Release.Name }}
  ports:
    - name: rtc-tcp
      port: 8083
      protocol: TCP
      targetPort: 8083
      nodePort: {{ .Values.service.nodeport }}
    - name: rtc-udp
      port: 8083
      protocol: UDP
      targetPort: 8083
      nodePort: {{ .Values.service.nodeport }}
  sessionAffinity: None
  type: LoadBalancer