apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  name: biggochat-service
  namespace: mattermost
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: biggochat-leader
  namespace: mattermost
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ''
    resources:
      - services
    verbs:
      - get
      - list
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: biggochat-leader
  namespace: mattermost
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: biggochat-leader
subjects:
  - kind: ServiceAccount
    name: biggochat-service
    namespace: mattermost
