package model

const (
	CustomChannelReadOnlyRoleCreationMigrationKey = "CustomChannelReadOnlyRoleCreationMigrationComplete"
	CustomSystemVerifiedRoleCreationMigrationKey = "CustomSystemVerifiedRoleCreationMigrationComplete"
	CustomVerifiedTierMigrationMigrationKey = "CustomVerifiedTierMigrationMigrationComplete"
)
